---
title: "Final Project Part A: Risk-Neutral Monte Carlo Pricing"
subtitle: "DATA 5695: Computational Methods in FinTech"
---

# Introduction 

This final project is a capstone for all we have learned about how to apply risk-neutral pricing theory to the Monte Carlo pricing of exotic option payoffs. The main focus is on applying the logic of control variate sampling. We will also introduce more complex dynamics in the second problem where we will simulate a stochastic volatility model of asset prices. 

Control variate sampling will be our point of departure from the risk-neutral approach and into a truly catallactic approach. From the risk-neutral paradigm Clewlow & Carverhill suggest that we can take inspiration from practitioners and their hedging practices for guidance regarding the choice of control variates. This is a good starting place. We will reinterpret this under the catallactic paradigm. To the catallactist real-world hedges are the result of subject control variates. These two worlds are roughly isomorphic, but it's at least a little bit confusing under the risk-neutral paradigm given that the asset price is already assumed to have been hedged.    

## Problem 1: Pricing and Arithmetic Asian Option

This example is taken from Chapter 4 of the book *Implementing Derivatives Models* by Clewlow and Strickland. In this project you will price a European arithmetic Asian call option. This option pays the difference (if positive) between the arithmetic average of the asset price $A_{T}$ and the strike price $K$ at the maturity date $T$. The arithmetic average is taken on a set of observations (called fixings) of the asset price $S_{t_{i}}$ (which we assume follows geometric Brownian motion) at dates $t_{i}; i = 1 \ldots N$.

$$
A_{T} = \frac{1}{N} \sum\limits_{i=1}^{N} S_{t_{i}}
$$

There is no analytical solution for the price of an arithmetic Asian option; however, there is a simple analytical formula for the price of a geometric Asian option. A geometric Asian call option pays the difference (again, only if positive) between the geometric average of the asset price $G_{T}$ and the strike price $K$ at the maturity date $T$. The geometric average is defined as

$$
G_{T} = \left( \prod\limits_{i=1}^{N} S_{t_{i}} \right) ^{1/N}
$$

Since the geometric average is essentially the product of lognormally distributed variables then it is also lognormally distributed. Therefore the price of the geometric Asian call option is given by a modified Black--Scholes formula:

$$
C_{GA} = exp(-rT) \left(exp(a + \frac{1}{2}b) N(x) - K N(x - \sqrt{b}) \right)
$$

where

$$\begin{aligned}
a        &=& \ln{(G_{t})} + \frac{N - m}{N} \left( \ln{(S)} + \nu (t_{m+1} - t) + \frac{1}{2} \nu (T - t_{m+1}) \right) \\
b        &=& \frac{(N - m)^{2}}{N^{2}} \sigma^{2}(t_{m+1} - t) + \frac{\sigma^{2} (T - t_{m+1})}{6 N^{2}} (N - m) (2(N - m) - 1)  \\
\nu &=& r - \delta - \frac{1}{2} \sigma^{2} \\
x        &=& \frac{a - \ln{(K)} + b}{\sqrt{b}}
\end{aligned}$$

where $G_{t}$ is the current geometric average and $m$ is the last known fixing. The geometric Asian option makes a good static hedge style control variate for the arithmetic Asian option. To implement the Monte Carlo method we simulate the difference between the arithmetic and geometric Asian options or a hedged portfolio which is long one arithmetic Asian and short one geometric Asian option. This is much faster than using the delta of the geometric Asian option to generate a delta hedge control variate because we do not have to compute the delta at every time step and it is equivalent to a continuous delta hedge.

For this project we will price a $1$--year maturity, European Asian call option with a strike price of $\$100$, a current asset price at $\$100$ and a volatility of $20\%$. The continuously compounded interest rate is assumed to be $6\%$ per annum, the asset pays a continuous dividend yield of $3\%$ per annum, and their are $10$ equally spaced fixing dates. The simulation has $10$ time steps and $100$ simulations; $K = \$100$, $T = 1$ year, $S = \$100$, $\sigma = 0.2$, $r = 0.06$, $\delta = 0.03$, $N = 10$, $M = 10000$.

The model for asset price dynamics at each time step is Geometric Brownian Motion, as follows

$$
S_{t} = S_{t-1} \times \exp{(nudt + sigsdt  \times \varepsilon)}
$$


where $\varepsilon$ is drawn from a standard normal distribution.

A good idea is to precompute the constants as follows:

$$\begin{aligned}
dt        &=& \Delta t  = \frac{T}{N} = \frac{1}{10} = 0.1 \\
nudt     &=& (r - \delta - \frac{1}{2} \sigma^{2}) \Delta t = (0.06 - 0.03 - 0.5 \times 0.2^{2}) \times 0.1 = 0.001 \\
sigsdt   &=& \sigma \sqrt{\Delta t} = 0.2 \sqrt{0.1} = 0.0632
\end{aligned}$$

Then for each simulation $j = 1$ to $M$ where $M = 10,000$, $S_{t}$ is initialised to $S = 100$, $sumSt = 0$ and $productSt = 1$. Then for each time step $i = 1$ to $N$, where $N = 10$, $S_{t}$ is simulated and the sum and product of the asset prices at the fixing times are accumulated.

The estimate of the option price is

$$\hat{C_{0}} = \frac{1}{M} \sum\limits_{i=1}^{M} C_{0,j}$$

where

$$C_{0,j} = \exp{(-rT)} C_{T,j}$$

and

$$C_{T,j} = \max{(0, A_{T} - K)}.$$

A measure of the simulation error is the standard deviation of $\hat{C_{0}}$ which is called the standard error $SE(\: \cdot \:)$ and can be estimated as the sample standard deviation of $C_{0,j}$ divided by the square root of the number of samples.

$$SE(\hat{C_{0}}) = \frac{SD(C_{0,j})}{\sqrt{M}}$$

where

$$SD(C_{0,j}) = \sqrt{\frac{1}{M-1} \sum\limits_{j=1}^{M} (C_{0,j} - \hat{C_{0}})^{2}}$$

The deliverable for this project, in addittion to the project source code, is a table that presents the results of the simulation. In the table present the price, standard error, and relative computation time for the following:

-   Simple Monte Carlo

-   Antithetic sampling

-   Control variate

-   Antithetic and control variate

Finally, give a brief statement about your conclusion regarding the trade--off between computation time and variance reduction costs.


## Problem 2: Pricing a Lookback Option

This example is taken from Chapter 4 of the book *Implementing Derivatives Models* by Clewlow and Strickland. In this project you will price a European fixed strike lookback call option. This option pays the difference, if positive, between the maximum of a set of observations (called fixings) of the asset price $S_{t_{i}}$ at dates $t_{i}; i = 1, \ldots, N$ and the strike price. Thus the payoff at the maturity date is

$$\max{(0, \max{(S_{t_{i}}; i = 1, \ldots, N)} - K)}$$

We will also assume that the asset price and the variance of the asset price returns $V = \sigma^{2}$ are governed by the following stochastic differential equations:

$$\begin{aligned}
dS &=& r S dt + \sigma S dz_{1} \\
dV &=& \alpha (\bar{V} - V) dt + \xi \sqrt{V} dz_{2}
\end{aligned}$$

and that the Wiener processes $dz_{1}$ and $dz_{2}$ are uncorrelated, though this can easily be generalized.

There is no analytical solution for the price of a European fixed strike lookback call option with discrete fixings and stochastic volatility.  However, there is a simple analytical formula for the price of a continuous fixing fixed strike lookback call with constant volatility.

$$\begin{gathered}
C_{FSLBCall} = G + Se^{\delta T} N(x + \sigma \sqrt{T}) - Ke^{-rT}N(x) \\
                                  -\frac{S}{B} \left( e^{-rT} \left(\frac{E}{S} \right)^{B} N(x + (1 - B) \sigma \sqrt{T}) 
                                 -e^{-\delta T} N(x + \sigma \sqrt{T}) \right)
\end{gathered}$$

where

$$\begin{cases} \mbox{if} \quad K \ge M, & \, \mbox{then} \quad E = K, G = 0 \\
              \mbox{if} \quad K <   M, & \, \mbox{then} \quad E = M, G = e^{-rT}(M - K) \end{cases}$$

and

$$\begin{aligned}
B &=& \frac{2(r - \delta)}{\sigma^{2}} \\
x &=& \frac{\ln{\left(\frac{S}{E}\right)} + \left((r-\delta) - \frac{1}{2}\sigma^{2} \right)T}{\sigma \sqrt{T}}
\end{aligned}$$

and $M$ is the current known maximum. We can therefore use the continuously fixed floating strike lookback call option formula to compute *delta*, *gamma*, and *vega* hedge control variates. Rather than differentiate the above equation with respect to the asset price twice and volatility once which would lead to extremely complex expressions it is more efficient to use finite difference approximations to the partial differentials for *gamma* and *vega*.

A measure of the simulation error is the standard deviation of $\hat{C_{0}}$ which is called the standard error $SE(\: \cdot \:)$ and can be estimated as the sample standard deviation of $C_{0,j}$ divided by the square root of the number of samples.

$$SE(\hat{C_{0}}) = \frac{SD(C_{0,j})}{\sqrt{M}}$$

where

$$SD(C_{0,j}) = \sqrt{\frac{1}{M-1} \sum\limits_{j=1}^{M} (C_{0,j} - \hat{C_{0}})^{2}}$$

The deliverable for this project, in addittion to the project source code, is a table that presents the results of the simulation. For example, fill in the missing data for the following table:

  -------------------- ------- ---------- -------------
                                Standard   Computation
                        Price    Error        Time
  Simple estimate                         
  Antithetic variate                      
  Control variates                        
  Combined variates                       
  -------------------- ------- ---------- -------------

The parameters for the problem are given in the following table.

  ---------------------------------- --------
  Strike Price                            100
  Time to Maturity                     1 year
  Initial asset price                     100
  Volatility                           $20\%$
  Risk--free rate                       $6\%$
  Continuous Dividend Yield             $3\%$
  Mean reversion rate ($\alpha$)          5.0
  Volatility of Volatility ($\xi$)       0.02
  Number of time steps                     52
  Number of simulations                  1000
  ---------------------------------- --------